apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  selector:
    app: iris
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
spec:
  selector:
    matchLabels:
      app: iris
  replicas: 2
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris
        image: nicolacucina/iris-prova:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000