apiVersion: v1
kind: Service
metadata:
  name: iris-server-service
spec:
  selector:
    app: iris-server
  ports:
  - protocol: "TCP"
    port: 6002
    targetPort: 6001
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-service
spec:
  selector:
    matchLabels:
      app: iris-service
  replicas: 1
  template:
    metadata:
      labels:
        app: iris-service
    spec:
      containers:
      - name: iris-service
        image: nicolacucina/iris-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6001