apiVersion: v1
kind: Service
metadata:
  name: hello-user-service
  namespace: default
spec:
  selector:
    app: hello-server
  ports:
  - protocol: "TCP"
    port: 6002
    targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: hello-admin-service
  namespace: default
spec:
  selector:
    app: hello-server
  ports:
  - protocol: "TCP"
    port: 6003
    targetPort: 8081
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-server
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
      - name: hello-server
        image: nicolacucina/altro-hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8081
